---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: check-executables-have-shebangs

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.15
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.10.0
    hooks:
      - id: helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
