apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: workflows
  destination:
    name: in-cluster
    namespace: workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/james-gonzalez/argo-local
    path: workflows
    targetRevision: HEAD
